callbacks:
- RichModelSummary:
    max_depth: 4
    show_hyperparameters: true
  name: RichModelSummary
- ModelCheckpoint:
    filename: '{epoch:02d}-{val_loss:.2f}'
    mode: min
    monitor: val_loss
    save_last: true
    save_top_k: 3
    verbose: true
  name: ModelCheckpoint
- ModelCheckpoint:
    filename: '{epoch:02d}-{val_pr_auc:.2f}'
    mode: max
    monitor: val_pr_auc
    save_last: false
    save_top_k: 3
    verbose: true
  name: ModelCheckpoint
- ModelCheckpoint:
    filename: '{epoch:02d}-{val_f1:.2f}'
    mode: max
    monitor: val_f1
    save_last: false
    save_top_k: 3
    verbose: true
  name: ModelCheckpoint
- EarlyStopping:
    min_delta: 1.0e-06
    mode: max
    monitor: val_pr_auc
    patience: 5
    verbose: true
  name: EarlyStopping
- LearningRateMonitor:
    logging_interval: step
  name: LearningRateMonitor
- RichProgressBar: {}
  name: RichProgressBar
- GradientNormLogger:
    clip_alpha: 0.97
    clip_eps: 1.0e-06
    clip_factor: 1.0
    clip_max_norm: 1.0
    clip_mode: zscore
    clip_option: adaptive_scaling
    clip_skip_update_on_spike: false
    clip_warmup_steps: 10
    clip_z_thresh: 2.5
    log_every_n_steps: 50
    log_global_norm: true
    log_histograms: false
    log_module_norms: false
    log_param_norms: false
    log_percentiles: false
    log_sparsity: true
    modules_to_track: null
    norm_type: 2.0
    use_adaptive_clipping: true
  name: GradientNormLogger
- MetricsEvaluationCallback:
    window_overlap: 0.5
  name: MetricsEvaluationCallback
- CalibrationDiagnosticCallback:
    log_every_n_epochs: 1
    n_bins: 10
  name: CalibrationDiagnosticCallback
data:
  MEGOnTheFlyDataModule:
    auto_generate_splits: true
    cache_dir: /sps/crnl/eliasB/data/processed/meg_preprocessing
    dataloader_config:
      test:
        batch_size: 1
        drop_last: false
        num_workers: 4
        pin_memory: true
        shuffle: false
        worker_init_fn: null
      train:
        batch_size: 32
        drop_last: true
        num_workers: 4
        pin_memory: true
        shuffle: true
        worker_init_fn: null
      val:
        batch_size: 32
        drop_last: false
        num_workers: 4
        pin_memory: true
        shuffle: false
        worker_init_fn: null
    dataset_config:
      annotation_rules:
        Default:
          exclude:
          - true_spike
          - detected_spike
          - bad_1
          include: []
        Holdout:
          exclude: []
          include:
          - jj_add
          - JJ_add
          - jj_valid
          - JJ_valid
        IterativeLearningFeedback:
          exclude:
          - detected_spike
          - bad_1
          include: []
        MEG:
          exclude: []
          include:
          - event
        Omega:
          exclude: []
          include: []
      estimated_spike_duration_s: 0.1
      first_half_spike_duration: 0.05
      h_freq: 99.0
      l_freq: 1.0
      median_filter_temporal_window_ms: 0.0
      n_windows: 20
      noise_level: 0.1
      normalization:
        axis: null
        epsilon: 1.0e-20
        method: robust_zscore
        percentile: 95
      notch_freq: 50.0
      patient_group_mappings:
        Holdout: Holdout
        IterativeLearningFeedback1: IterativeLearningFeedback
        IterativeLearningFeedback2: IterativeLearningFeedback
        MEG: MEG
        Omega: Omega
      sampling_rate: 200
      second_half_spike_duration: 0.05
      skip_files:
      - .*brana_Epi-001_20100420_05.*
      - .*P283/p1.*
      - .*P30/p4.*
      special_case_handling:
        Liogier_AllDataset1200Hz:
        - MRO22-2805
        - MRO23-2805
        - MRO24-2805
      spike_overlap_threshold: 0.0
      window_duration_s: 0.2
      window_overlap: 0.5
    dataset_name: OnlineWindowDataset
    fold: '1'
    force_preprocess: false
    n_folds: 5
    prepare_data_per_node: false
    preprocessed_dir: /sps/crnl/eliasB/data/processed/preprocessed_recordings
    reference_coordinates: /pbs/home/e/eboulanger/repositories/meg-spike-detection/configs/reference_channels.pkl
    root_dirs:
    - /sps/crnl/pmouches/data/all_clean_patients
    samples_per_recording: 90
    splits_dir: /sps/crnl/eliasB/data/processed/cv_splits
  name: MEGOnTheFlyDataModule
error_handling:
  include_traceback: true
  log_exceptions: true
  max_traceback_depth: 10
evaluation:
  compute_relaxed: true
  default_threshold: 0.5
  metrics_list:
  - pr_auc
  - roc_auc
  - accuracy
  - balanced_accuracy
  - f1
  - precision
  - recall
  temperature_scaling: false
  test_threshold_optimization: false
  threshold_optimization: true
experiment:
  checkpoint_path: null
  name: HBIOT-ISBI/meg_spike_detection-200ms-200Hz-raw-HBIOT-0.5overlap-fold1
  seed: 42
  version: context_len-cls-20win-bs32
logging:
  log_dir: /sps/crnl/eliasB/logs
  log_level: INFO
  pipeline_log: /sps/crnl/eliasB/logs/pipeline.log
  separator:
    char: '='
    length: 50
loss:
  FocalLoss:
    alpha: 0.25
    gamma: 2.0
    smoothing: false
  name: FocalLoss
model:
  BIOT:
    attn_dropout: 0.2
    contextual: false
    depth: 4
    emb_size: 256
    ff_dropout: 0.2
    heads: 4
    linear_attention: false
    mode: raw
    n_selected_tokens: 3
    overlap: 0.5
    selection_temperature: 1.0
    sequential_processing: false
    sfreq: 400.0
    token_size: 40
  BIOTHierarchical:
    classifier:
      dropout: 0.2
      num_heads: 8
    contextual: true
    emb_size: 256
    heads: 4
    input_shape:
    - 20
    - 275
    - 40
    inter_window_depth: 4
    linear_attention: false
    log_dir: /sps/crnl/eliasB/logs/HBIOT-ISBI/meg_spike_detection-200ms-200Hz-raw-HBIOT-0.5overlap-fold1/context_len-cls-20win-bs32
    mode: raw
    overlap: 0.5
    reference_coordinates: /pbs/home/e/eboulanger/repositories/meg-spike-detection/configs/reference_channels.pkl
    sequential_processing: false
    token_selection:
      n_selected_tokens: 0
      selection_temperature: 1.0
      use_cls_token: true
      use_max_pool: false
      use_mean_pool: 0
      use_min_pool: false
    token_size: 20
    transformer:
      attn_dropout: 0.2
      ff_dropout: 0.2
    window_encoder_depth: 4
  FAMED:
    ch_num: 275
    drop_connect_rate: 0.2
    inplanes: 16
    layers:
    - 2
    - 2
    - 2
    - 2
  SFCN:
    conv_channels:
    - 32
    - 64
    - 128
    - 256
    - 64
    conv_kernel_sizes:
    - 5
    - 5
    - 5
    - 5
    - 1
    dropout: 0.5
    pool_kernel_size: 2
  name: BIOTHierarchical
optimizer:
  AdamW:
    lr: 0.0003
    weight_decay: 0.0001
  name: AdamW
scheduler:
  CosineAnnealingLR:
    T_max: 50
  CosineAnnealingWarmRestarts:
    T_0: 2
    T_mult: 1
    eta_min: 1.0e-05
  OneCycleLR:
    anneal_strategy: cos
    div_factor: 100.0
    final_div_factor: 10000.0
    max_lr: 0.001
    pct_start: 0.3
    three_phase: false
  ReduceLROnPlateau:
    factor: 0.5
    min_lr: 1.0e-07
    mode: min
    patience: 3
  StepLR:
    gamma: 0.1
    step_size: 10
  name: ReduceLROnPlateau
  warmup:
    enabled: false
    warmup_end_lr: 0.0003
    warmup_epochs: 5
    warmup_start_lr: 1.0e-06
trainer:
  accelerator: auto
  devices: auto
  enable_model_summary: true
  enable_progress_bar: true
  gradient_clip_val: null
  limit_test_batches: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  log_every_n_steps: 50
  max_epochs: 100
  precision: bf16-mixed
  profiler: null
